# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:14
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests
      - run:
          command: npm build
          name: Build app

workflows:
  on_commit:
    jobs:
      - build_and_test
